import React, { useState, useEffect, useRef } from 'react';
import Sidebar from './components/Sidebar';
import Dashboard from './components/Dashboard';
import RealTimeMonitor from './components/RealTimeMonitor';
import TrainingSimulator from './components/TrainingSimulator';
import CodeGenerator from './components/CodeGenerator';
import AlertToast from './components/AlertToast';
import { ViewState, Packet, ThreatLevel, AttackType, Alert, ConnectionStatus } from './types';
import { analyzePacketThreat } from './services/geminiService';
import { predictPacketThreat, mapPredictionToThreatData, testBackendConnection } from './services/idsBackendService';
import { AlertTriangle, Loader2 } from 'lucide-react';

const App: React.FC = () => {
  const [view, setView] = useState<ViewState>(ViewState.DASHBOARD);
  const [packets, setPackets] = useState<Packet[]>([]);
  const [activeAlert, setActiveAlert] = useState<Alert | null>(null);
  const [selectedPacketForAnalysis, setSelectedPacketForAnalysis] = useState<Packet | null>(null);
  const [analysisResult, setAnalysisResult] = useState<string>('');
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  
  // Session Statistics (Cumulative)
  const [sessionStats, setSessionStats] = useState({ total: 0, threats: 0 });

  // Real-Time Connection State
  const [connectionStatus, setConnectionStatus] = useState<ConnectionStatus>(ConnectionStatus.DISCONNECTED);
  const [isSimulating, setIsSimulating] = useState(true);
  const wsRef = useRef<WebSocket | null>(null);
  const reconnectTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  // WebSocket Connection Logic
  const connectToBackend = () => {
    if (wsRef.current) {
      // Manual Disconnect
      if (wsRef.current.readyState === WebSocket.OPEN) {
        wsRef.current.close();
      }
      wsRef.current = null;
      setConnectionStatus(ConnectionStatus.DISCONNECTED);
      return;
    }

    setConnectionStatus(ConnectionStatus.CONNECTING);
    setIsSimulating(false); // Stop simulation when connecting

    try {
      // Connect to the Python backend generated by CodeGenerator
      const socket = new WebSocket('ws://localhost:8765');
      
      socket.onopen = () => {
        setConnectionStatus(ConnectionStatus.CONNECTED);
        console.log("Connected to IDS Backend");
        if (reconnectTimeoutRef.current) clearTimeout(reconnectTimeoutRef.current);
      };

      socket.onmessage = (event) => {
        try {
          const data = JSON.parse(event.data);
          // Expecting data to match Packet interface partially
          const newPacket: Packet = {
            id: data.id || Math.random().toString(36).substr(2, 9),
            timestamp: data.timestamp || new Date().toLocaleString(),
            sourceIP: data.sourceIP || 'Unknown',
            destIP: data.destIP || 'Unknown',
            protocol: data.protocol || 'TCP',
            length: data.length || 0,
            flag: data.flag || 'None',
            threatLevel: (data.threatLevel as ThreatLevel) || ThreatLevel.LOW,
            attackType: (data.attackType as AttackType) || AttackType.NORMAL,
            confidence: data.confidence || 0,
            features: data.features || {}
          };
          addPacket(newPacket);
        } catch (e) {
          console.error("Failed to parse packet", e);
        }
      };

      socket.onclose = () => {
        setConnectionStatus(ConnectionStatus.DISCONNECTED);
        wsRef.current = null;
        // If we were trying to connect and failed, maybe revert to simulation so user sees activity?
        // For now, we stay disconnected to show the user they need to run the server.
      };

      socket.onerror = () => {
        setConnectionStatus(ConnectionStatus.ERROR);
        wsRef.current = null;
      };

      wsRef.current = socket;
    } catch (e) {
      setConnectionStatus(ConnectionStatus.ERROR);
    }
  };

  // Attempt to auto-connect on mount, if fails, it stays in simulation mode (which is visually "Online")
  useEffect(() => {
      // We start in Simulation mode by default so the user sees a "Green" system immediately.
      // connectToBackend(); // Uncommenting this would force a connection attempt, but might show Error if backend is off.
      // Keeping default simulation is safer for the "Green Button" requirement unless backend is ready.
  }, []);

  const addPacket = (newPacket: Packet) => {
    // Update cumulative stats
    setSessionStats(prev => ({
      total: prev.total + 1,
      threats: newPacket.attackType !== AttackType.NORMAL ? prev.threats + 1 : prev.threats
    }));

    setPackets(prev => {
        const updated = [...prev, newPacket];
        return updated.slice(-100); // Keep last 100
    });
    
    // Alert Logic
    if (newPacket.threatLevel === ThreatLevel.HIGH || newPacket.threatLevel === ThreatLevel.CRITICAL) {
      setActiveAlert({
        id: newPacket.id,
        packetId: newPacket.id,
        type: newPacket.attackType,
        level: newPacket.threatLevel,
        timestamp: newPacket.timestamp,
        message: `High confidence ${newPacket.attackType} attack detected from ${newPacket.sourceIP}`
      });
    }
  };

  // Simulation Logic
  useEffect(() => {
    let interval: ReturnType<typeof setInterval>;

    if (isSimulating && connectionStatus !== ConnectionStatus.CONNECTED) {
      interval = setInterval(async () => {
        const isAttack = Math.random() > 0.9; // 10% chance of attack in sim
        const attackTypes = [AttackType.DOS, AttackType.PROBE, AttackType.U2R, AttackType.DDOS];
        const type = isAttack 
          ? attackTypes[Math.floor(Math.random() * attackTypes.length)] 
          : AttackType.NORMAL;

        const newPacket: Packet = {
          id: Math.random().toString(36).substr(2, 9),
          timestamp: new Date().toLocaleString(),
          sourceIP: `192.168.1.${Math.floor(Math.random() * 255)}`,
          destIP: `10.0.0.${Math.floor(Math.random() * 255)}`,
          protocol: Math.random() > 0.5 ? 'TCP' : 'UDP',
          length: Math.floor(Math.random() * 1500),
          flag: isAttack ? 'SYN_FLOOD' : 'ACK',
          threatLevel: isAttack ? (Math.random() > 0.5 ? ThreatLevel.HIGH : ThreatLevel.MEDIUM) : ThreatLevel.LOW,
          attackType: type,
          confidence: isAttack ? 0.85 + Math.random() * 0.14 : 0.01,
          features: { 'src_bytes': Math.random(), 'dst_bytes': Math.random() }
        };

        // Try to get real prediction from backend
        try {
          const prediction = await predictPacketThreat(newPacket);
          if (prediction) {
            // Update packet with backend prediction results
            const { threatLevel, attackType } = mapPredictionToThreatData(
              prediction.prediction,
              newPacket.confidence
            );
            newPacket.threatLevel = threatLevel;
            newPacket.attackType = attackType;
          }
        } catch (e) {
          // If backend is not available, use simulated values
          console.debug('Backend not available, using simulated threat prediction');
        }

        addPacket(newPacket);
      }, 1500);
    }

    return () => clearInterval(interval);
  }, [isSimulating, connectionStatus]);

  const handleAnalyzePacket = async (packet: Packet) => {
    setIsAnalyzing(true);
    setSelectedPacketForAnalysis(packet);
    setAnalysisResult('');
    
    try {
      // Call the backend ML model for prediction
      const prediction = await predictPacketThreat(packet);
      
      // Format the result for display
      const analysisText = `
Threat Prediction Result:
━━━━━━━━━━━━━━━━━━━━━━
Status: ${prediction.alert}
Confidence: ${Math.round((packet.confidence || 0) * 100)}%
Label: ${prediction.label}
Model Prediction: ${prediction.prediction === 1 ? 'ATTACK DETECTED' : 'NORMAL TRAFFIC'}

Additional Details:
- Source IP: ${packet.sourceIP}
- Destination IP: ${packet.destIP}
- Protocol: ${packet.protocol}
- Packet Length: ${packet.length} bytes
- Threat Level: ${packet.threatLevel}

Analysis by: IDS ML Model (Random Forest)
      `;
      
      setAnalysisResult(analysisText);
    } catch (error) {
      console.error('Analysis failed:', error);
      setAnalysisResult('Failed to analyze packet. Please ensure the backend is running at http://127.0.0.1:8000');
    }
    
    setIsAnalyzing(false);
  };

  // Check if system is effectively "active" (either real connection or simulation)
  const isSystemActive = connectionStatus === ConnectionStatus.CONNECTED || isSimulating;

  return (
    <div className="flex h-screen bg-slate-950 text-slate-200 overflow-hidden font-sans">
      <Sidebar currentView={view} setView={setView} />
      
      <main className="flex-1 flex flex-col min-w-0 relative">
        {/* Top Bar */}
        <div className="h-16 border-b border-slate-800 bg-slate-900/50 backdrop-blur flex items-center justify-between px-6">
           <h2 className="font-semibold text-slate-100 flex items-center gap-2">
             {view === ViewState.DASHBOARD && 'Operational Dashboard'}
             {view === ViewState.REALTIME && 'Real-Time Packet Monitor'}
             {view === ViewState.TRAINING && 'AI Model Training Center'}
             {view === ViewState.CODE_GEN && 'System Source Code'}
           </h2>
           <div className="flex items-center gap-4 text-xs font-mono">
             <div className={`flex items-center gap-2 px-3 py-1 rounded-full border transition-all ${
                isSystemActive 
                ? 'bg-emerald-950 border-emerald-500/50 text-emerald-400 shadow-[0_0_10px_rgba(16,185,129,0.3)]' 
                : 'bg-slate-900 border-slate-700 text-slate-500'
             }`}>
                <div className={`w-2 h-2 rounded-full ${isSystemActive ? 'bg-emerald-500 animate-pulse' : 'bg-slate-500'}`}></div>
                {connectionStatus === ConnectionStatus.CONNECTED ? 'SYSTEM ONLINE (LIVE SOCKET)' : (isSimulating ? 'SYSTEM ONLINE' : 'SYSTEM OFFLINE')}
             </div>
             <span className="text-slate-500">IDS v1.0 PRO</span>
           </div>
        </div>

        {/* Content Area */}
        <div className="flex-1 overflow-auto p-6 relative">
            <div className="scan-line"></div>
            {view === ViewState.DASHBOARD && (
              <Dashboard 
                packets={packets} 
                totalPackets={sessionStats.total}
                totalThreats={sessionStats.threats}
              />
            )}
            {view === ViewState.REALTIME && (
              <RealTimeMonitor 
                packets={packets} 
                onAnalyze={handleAnalyzePacket}
                connectionStatus={connectionStatus}
                onToggleConnection={connectToBackend}
                isSimulating={isSimulating}
                onToggleSimulation={() => setIsSimulating(!isSimulating)}
              />
            )}
            {view === ViewState.TRAINING && <TrainingSimulator />}
            {view === ViewState.CODE_GEN && <CodeGenerator />}
        </div>

        {/* Analysis Modal */}
        {selectedPacketForAnalysis && (
            <div className="absolute inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-40 p-4">
                <div className="bg-slate-900 border border-slate-700 rounded-lg p-6 max-w-lg w-full shadow-2xl animate-in zoom-in-95 duration-200">
                    <h3 className="text-lg font-bold text-white mb-2 flex items-center gap-2">
                      <AlertTriangle className="text-emerald-500" size={20} />
                      Packet Analysis Report
                    </h3>
                    <div className="bg-slate-950 p-3 rounded mb-4 text-xs font-mono text-slate-400 border border-slate-800">
                        ID: {selectedPacketForAnalysis.id}<br/>
                        SRC: {selectedPacketForAnalysis.sourceIP} | DST: {selectedPacketForAnalysis.destIP}
                    </div>
                    <div className="text-sm text-slate-300 leading-relaxed min-h-[100px]">
                        {isAnalyzing ? (
                            <div className="flex flex-col items-center justify-center h-24 gap-3 text-emerald-400">
                                <Loader2 className="animate-spin" />
                                <span className="text-xs">Querying AI Analyst...</span>
                            </div>
                        ) : (
                            analysisResult
                        )}
                    </div>
                    <button 
                        onClick={() => setSelectedPacketForAnalysis(null)}
                        className="mt-6 w-full bg-slate-800 hover:bg-slate-700 py-2 rounded text-sm font-medium transition-colors border border-slate-700 hover:text-white"
                    >
                        Close Report
                    </button>
                </div>
            </div>
        )}

        <AlertToast alert={activeAlert} onClose={() => setActiveAlert(null)} />
      </main>
    </div>
  );
};

export default App;